### ISSUE TITLE
0.8 Helm Generated YAML not parsing

### ISSUE THREAD

**Issue by blaketastic2** [Liujingfang1/istio#1]
Thanks for working on this. I was curious if you had tried to work with a single consolidated YAML with Kustomize? What I did was use the "helm template" command to generate the 0.8 YAML, but Kustomize seems to run into issues when parsing the YAML. Have you been able to get this to work with 0.8? If so, I'm curious how.

**Comment by Liujingfang1** [comment]
@blaketastic2 I tried it previously, but failed to get it work with kustomize.
